### ISSUE TITLE
Pb url cryosat2

### ISSUE THREAD

**Issue by tarchambault** [ocean-data-challenges/2021a_SSH_mapping_OSE#4]
Bonjour, merci pour ces données et ce challenge très intéressant,
Je reporte juste une petite faute de frappe aux conséquences potentiellement importantes. Dans le Notebook d'exemple d'accès aux données d'aviso l'url des données cryosat est incorrecte.
Merci beaucoup pour ce travail dans tout les cas.

Théo Archambault
Doctorant Sorbonne Université LIP6

**Comment by mballaro** [comment]
Bonjour Théo,
Merci pour ton message et pour avoir rapporté cette erreur d'url.
Nous avons corrigé le notebook.

**Comment by tarchambault** [comment]
Pas de soucis,
J'ai une autre question : quelle est la différence entre le 4DvarNet et le 4DVarNet V2022 qui a de meilleures performances. De plus la méthode MIOST utilise t'elle des données doppler supplémentaire comme expliquée dans l'article associé ou se base t'elle uniquement sur ce qui est proposé ici?
Merci d'avance.

**Comment by mballaro** [comment]
Bonjour Théo,
Concernant la cartographie 4dvarnet v2021 vs v2022, il me semble qu'il s'agit d'une evolution de l'algo ou de correction de bug dans l'ancienne version. Maxime Beauchamp (https://github.com/maxbeauchamp) ou Ronan Fablet (https://github.com/rfablet) de l'IMT Atlantique pourront mieux t'éclairer que moi sur les évolutions du 4Dvarnet. Concernant la méthode MIOST, présentée dans ce data-challenge, elle se base uniquement sur la reconstruction de la géostrophie à partir des altimètres nadirs proposés dans ce data-challenge (elle n'utilise pas de données supplémentaires).
